### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by garygreen** [yashprit/make-beep#1]
> Error: Cannot find module './'

Also your usage syntax is wrong:

``` javascript
var makeBeep = require('make-beep');

make-beep(1);
```

**Comment by yashprit** [comment]
Yeah I know, I added and become so lazy, I'll make correction today and published npm.

BTW, I have modified, README

Thanks for letting me know

**Comment by yashprit** [comment]
published latest package https://www.npmjs.com/package/make-beep
